
meta_product_name: "findYourTeam"
meta_title: "findYourTeam - from Gamer to CyberAthlete!"
meta_description: "If you are looking to take your gaming to the next level, finding a competitive team is essential. findYourTeam is the pinnacle of team building platforms and will make every step of forming or finding a team the easy part of competitive gaming."
meta_image: "findyourteam.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
